### ISSUE TITLE
Use asset tag in addons.xml

### ISSUE THREAD

**Issue by jez500** [eracknaphobia/plugin.video.simpsonsworld#1]
Hi,

Your icon/fanart don't get correctly recognized without the asset tag in your addon.xml
http://kodi.wiki/view/Addon.xml#.3Cassets.3E

Resulting in https://kodi.tv/addon/plugins-video-add-ons/simpsons-world

**Comment by eracknaphobia** [comment]
Thanks, I'm still getting used to the new layout changes in 17 ;-)
