### ISSUE TITLE
Auto-playing random episodes

### ISSUE THREAD

**Issue by hackthis02** [eracknaphobia/plugin.video.simpsonsworld#7]
When user clicks "Random Episode" after finishing episode, another random episode starts playing without user interaction.

**Comment by hackthis02** [comment]
I've looked into this but I don't see any player/xbmcplugin callbacks to tell us when a episode has finished playing. I thought maybe just load up the playlist with bunch of random episodes, enough that the user would never finish them in a sitting. Thoughts?

**Comment by eracknaphobia** [comment]
Yeah, that would work.  We could probably even build the playlist as the first random episode is playing by running the playlist build code after`  get_stream(url, info)` in the random episode function. That way the user doesn't have to sit and wait for the playlist to build. 10 episode enough? I suppose the amount could be a user setting and then we just hard cap it at 99.

**Comment by eracknaphobia** [comment]
Actually found a much nicer way to handle this by just adding the plugin mode to the video playlist .
https://github.com/eracknaphobia/plugin.video.simpsonsworld/commit/0cc25db338450da750aadbd96c7d11504ef756dd

**Comment by hackthis02** [comment]
I like that a lot. I'll pull it down tonight and give it a test.

**Comment by hackthis02** [comment]
Works great for me.
